config/routes.rb
ACMLadder::Application.routes.draw do
  resource :setting, :only => [:edit, :update], :path_names => { :edit => '' }

  devise_for :users, :path => 'u', :skip => :registrations
  devise_scope :user do
    resource :registration,
             :only => [:new, :create, :edit, :update],
             :path => 'u',
             :path_names => { :new => 'sign_up' },
             :controller => 'devise/registrations',
             :as => :user_registration
  end

  resources :users, :only => [:index, :show] do
    resources :submissions, :only => :index
  end
  post '/users' => 'users#index'

  resources :problems, :except => :destroy do
    resources :submissions, :only => [:create, :update]
    get 'submit' => 'submissions#new'
  end

  resources :submissions, :only => [:index, :show]

  root :to => 'home#index'

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :problem
  attr_accessible :code, :language
  validates_presence_of :user_id, :problem_id, :code, :language
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  load_and_authorize_resource

  def index
    params[:page] ||= 1
    begin
      @current_page = Integer(params[:page])
      if @current_page < 1
        flash[:alert] = "Kidding? The page you tell me is non-positive!"
        @current_page = 1
      end
    rescue ArgumentError
      flash[:alert] = "Kidding? The page you tell me is not a number!"
      @current_page = 1
    end
    if params[:user_id]
      user = User.find_by_handle(params[:user_id])
      if user_signed_in? && current_user.has_role?(:admin)
        @submissions = user.submissions.offset((@current_page - 1) * 10).last(10).reverse
      else
        @submissions = user.submissions.joins(:problem).where("`problems`.`level` != -1").offset((@current_page - 1) * 10).last(10).reverse
      end
    else
      if user_signed_in? && current_user.has_role?(:admin)
        @submissions = Submission.offset((@current_page - 1) * 10).last(10).reverse
      else
        @submissions = Submission.joins(:problem).where("`problems`.`level` != -1").offset((@current_page - 1) * 10).last(10).reverse
      end
    end
  end

  def new
    @problem = Problem.find(params[:problem_id])
    @submission.language = session[:lang]
  end

  def create
    @problem = Problem.find(params[:problem_id])
    @submission.problem = @problem
    @submission.user = current_user

    if @submission.save
      session[:lang] = @submission.language
      OJ.submit(@submission)	# delayed job
      redirect_to user_submissions_path(current_user), :notice => "Submit successfully."
    else
      flash[:alert] = "Failed to submit."
      render :action => :new
    end
  end

  def update
    @submission = Submission.new(params[:submission])
    create
  end

  def show
    if @submission.user_id != current_user.id && !current_user.has_role?(:admin)
      redirect_to submissions_path, :alert => "It's not for you..."
    end
    @problem = @submission.problem
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
  def get_submission_status(status)
    case status
    when :wait then ""
    when :comp, :run then "info"
    when :ac then "success"
    when :ce, :se then "warning"
    else "important"
    end
  end
end

app/views/submissions/index.html.erb
<% content_for :title do %>
  <% "Submissions" %>
<% end %>
<h2>Submissions</h2>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Handle</th>
      <th>Problem</th>
      <th>Status</th>
      <th>Language</th>
      <th>Submit Time</th>
    </tr>
  </thead>
  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><strong>
            <% if user_signed_in? && (current_user.has_role?(:admin) || submission.user_id == current_user.id) %>
              <%= link_to submission.id, submission_path(submission) %>
            <% else %>
              <%= submission.id %>
            <% end %>
        </strong></td>
        <td><%= link_to submission.user.handle, user_path(submission.user) %></td>
        <td>
          <div class="problem-label">
            <%= link_to submission.problem.level, "#{problems_path}?level=#{submission.problem.level}", :class => "label label-info" %>
            :
            <%= link_to submission.problem_id, problem_path(submission.problem_id), :class => "label label-success" %>
          </div>
        </td>
        <td>
          <% if user_signed_in? && (current_user.has_role?(:admin) || submission.user_id == current_user.id) && OJ::StatusIDToSym[submission.status] == :ce %>
            <%= link_to OJ::StatusIDToName[submission.status], submission_path(submission), :class => "btn btn-warning btn-mini" %>
          <% else %>
            <span class="label label-<%= get_submission_status(OJ::StatusIDToSym[submission.status]) %>">
              <%= OJ::StatusIDToName[submission.status] %>
            </span>
          <% end %>
        </td>
        <td>
          <% language = OJ::LangIDToName[submission.language] %>
          <% if user_signed_in? && (current_user.has_role?(:admin) || submission.user_id == current_user.id) %>
            <%= link_to language, submission_path(submission) %>
          <% else %>
            <%= language %>
          <% end %>
        </td>
        <td><%= submission.created_at.localtime.to_s(:db) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<ul class="pager">
  <% if @current_page > 1 %>
    <li class="previous">
    <a href="<%= "?page=#{@current_page - 1}" %>">&larr; Previous</a>
    </li>
  <% end %>
  <% unless @submissions.empty? %>
    <li class="next">
    <a href="<%= "?page=#{@current_page + 1}" %>">Next &rarr;</a>
    </li>
  <% end %>
</ul>

app/views/submissions/new.html.erb
<% content_for :title do %>
  <% "Submit Problem #{@problem.id}" %>
<% end %>
<h4>Submit Problem <%= @problem.id %> - <%= @problem.title %></h4>
<table class="table">
  <tbody>
    <tr>
      <td>
        <strong>Source</strong>
      </td>
      <td class="text-info">
        <%= "#{@problem.source} #{@problem.original_id}" %>
      </td>
      <td>
        <strong>EXP.</strong>
      </td>
      <td class="text-success">
        <strong><%= @problem.exp %></strong>
      </td>
      <td>
        <strong>Time Limit</strong>
      </td>
      <td class="text-warning">
        <%= @problem.time_limit %>MS
      </td>
      <td>
        <strong>Memory Limit</strong>
      </td>
      <td class="text-warning">
        <%= @problem.memory_limit %>KB
      </td>
    </tr>
  </tbody>
</table>
<%= simple_form_for [@problem, @submission] do |form| %>
  <fieldset>
    <%= form.input :language, :as => :radio_buttons, :item_wrapper_class => "inline", :collection => OJ.language_collection(@problem), :selected => session[:lang] %>
    <%= form.input :code, :input_html => { :class => "span8" } %>
  </fieldset>
  <div class="form-actions">
    <%= form.submit "Submit", :class => "btn btn-primary" %>
    <%= link_to "Back", :back, :class => "btn btn-danger pull-right" %>
  </div>
<% end %>

app/views/submissions/show.html.erb
<% content_for :title do %>
  <% "Submission Detail" %>
<% end %>
<h2>Submission Detail</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Handle</th>
      <th>Problem</th>
      <th>Status</th>
      <th>Language</th>
      <th>Submit Time</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @submission.id %></td>
      <td><%= link_to @submission.user.handle, user_path(@submission.user) %></td>
      <td>
        <div class="problem-label">
          <%= link_to @submission.problem.level, "#{problems_path}?level=#{@submission.problem.level}", :class => "label label-info" %>
          :
          <%= link_to @submission.problem_id, problem_path(@submission.problem_id), :class => "label label-success" %>
        </div>
      </td>
      <td>
        <span class="label label-<%= get_submission_status(OJ::StatusIDToSym[@submission.status]) %>">
          <%= OJ::StatusIDToName[@submission.status] %>
        </span>
      </td>
      <td><%= OJ::LangIDToName[@submission.language] %></td>
      <td><%= @submission.created_at.localtime.to_s(:db) %></td>
    </tr>
  </tbody>
</table>
<% if OJ::StatusIDToSym[@submission.status] == :ce %>
 <pre><%= @submission.error.html_safe %></pre>
<% end %>
<%= CodeRay.scan(@submission.code, OJ::LangIDToSym[@submission.language]).div.html_safe %>

<div class="form-actions">
  <center>
    <%= link_to "Quick Edit", "#submit-modal", :role => "button", :class => "btn btn-primary", :data => { :toggle => "modal" } %>
  </center>
</div>

<%= render 'layouts/submit-modal' %>

app/views/submissions/show_code.html.erb
<% content_for :title do %>
  <% "Code" %>
<% end %>
<h2>Code</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>User</th>
      <th>Problem</th>
      <th>Status</th>
      <th>Time</th>
      <th>Memory</th>
      <th>Language</th>
      <th>Submit Time</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @submission.id %></td>
      <td><%= link_to @submission.user.handle, user_path(@submission.user) %></td>
      <td><center><%= link_to @submission.problem_id, problem_path(@submission.problem_id) %></center></td>
      <td>
        <% status = status_list.invert[@submission.status] %>
        <% if user_signed_in? && (current_user.has_role?(:admin) || @submission.user_id == current_user.id) && status == "Compile Error" %>
          <%= link_to "Compile Error", submission_compile_error_path(@submission), :class => "btn btn-warning btn-mini" %>
        <% else %>
          <span class="label label-<%= get_submission_status(status) %>">
            <%= status %>
          </span>
        <% end %>
      </td>
      <td><%= "#{@submission.time}ms" if @submission.time %></td>
      <td><%= "#{@submission.memory}KB" if @submission.memory %></td>
      <td><%= language_list.invert[@submission.language] %></td>
      <td><%= @submission.created_at.localtime.to_s(:db) %></td>
    </tr>
  </tbody>
</table>
<%= CodeRay.scan(@submission.code, language_symbol[language_list.invert[@submission.language]]).div.html_safe %>