config/routes.rb
ACMLadder::Application.routes.draw do
  resource :setting, :only => [:edit, :update], :path_names => { :edit => '' }

  devise_for :users, :path => 'u', :skip => :registrations
  devise_scope :user do
    resource :registration,
             :only => [:new, :create, :edit, :update],
             :path => 'u',
             :path_names => { :new => 'sign_up' },
             :controller => 'devise/registrations',
             :as => :user_registration
  end

  resources :users, :only => [:index, :show] do
    resources :submissions, :only => :index
  end
  post '/users' => 'users#index'

  resources :problems, :except => :destroy do
    resources :submissions, :only => [:create, :update]
    get 'submit' => 'submissions#new'
  end

  resources :submissions, :only => [:index, :show]

  root :to => 'home#index'

end

app/views/layouts/_messages.html.erb
<% if show_announcement && !((announcement = get_announcement).blank?) && flash.empty? %>
  <div class="alert alert-block">
    <h4 class="alert-heading">Announcement</h4>
    <%= announcement.html_safe %>
  </div>
<% end %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= get_alert_class(name) %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to 'ACM Ladder', root_path, :class => 'brand' %>
<ul class="nav">
  <li class="<%= 'active' if params[:controller] == 'problems' %>">
  <%= link_to 'Problem', problems_path %>
  </li>
  <% if user_signed_in? %>
    <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Status
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to 'All Status', submissions_path %></li>
      <li><%= link_to 'My Status', user_submissions_path(current_user) %></li>
    </ul>
    </li>
  <% else %>
    <li class="<%= 'active' if params[:controller] == 'submissions' %>">
    <%= link_to 'Status', submissions_path %>
    </li>
  <% end %>
  <li class="<%= 'active' if params[:controller] == 'users' && params[:action] == 'index' %>">
  <%= link_to 'Ranking', users_path %>
  </li>
  <% if can? :manage, :all %>
    <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Manage
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li class="nav-header">
      Problem Admin
      </li>
      <li>
      <%= link_to "New Problem", new_problem_path %>
      </li>
      <% if params[:controller] == 'problems' && params[:action] == 'show' %>
        <li>
        <%= link_to "Edit Problem", edit_problem_path %>
        </li>
      <% end %>
      <li class="nav-header">
      Site Admin
      </li>
      <li>
      <%= link_to "Settings", edit_setting_path %>
      </li>
    </ul>
    </li>
  <% end %>
  <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Account
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <% if user_signed_in? %>
      <li>
      <%= link_to current_user.handle, user_path(current_user) %>
      </li>
      <li class="divider"></li>
      <li>
      <%= link_to 'Edit account', edit_user_registration_path %>
      </li>
      <li>
      <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
      </li>
    <% else %>
      <li>
      <%= link_to 'Login', new_user_session_path %>
      </li>
      <li>
      <%= link_to 'Sign up', new_user_registration_path %>
      </li>
    <% end %>
  </ul>
  </li>
</ul>
<%= link_to image_tag('forkme_right_red_aa0000.png', :id => "github-ribbon", :alt => "Fork me on GitHub"), ENV['GITHUB_LINK'] %>

app/views/layouts/_submit-modal.html.erb
<div id="submit-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="submit-label" aria-hidden="true">
  <%= simple_form_for [@problem, @submission], :html => { :style => "margin:0px" } do |form| %>
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="submit-label">Submit your code</h3>
    </div>
    <div class="modal-body">
      <fieldset>
        <%= form.input :language, :as => :radio_buttons, :item_wrapper_class => "inline", :collection => OJ.language_collection(@problem) %>
        <%= form.input :code, :input_html => { :style => "width:96%", :rows => 10 } %>
      </fieldset>
    </div>
    <div class="modal-footer">
      <%= form.submit "Submit", :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) + " &larr; ACM Ladder".html_safe : "ACM Ladder" %></title>
    <meta name="description" content="A level-based ACM-ICPC training site.">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
          <div class="row">
            <div class="wrapper span8 offset2">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <div class="row">
            <footer id="footer" class="span8 offset2">
            <div class="pull-right">
              footer: find me at app/views/layouts/application.html.erb
            </div>
            </footer>
          </div>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>